// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig, env } from "prisma/config";

// Prisma 7 does not read .env by itself under npm/node, so load it here (Node 20.12+).
try {
  process.loadEnvFile();
} catch {
  // no .env file: rely on variables already set in the environment
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
